version: '3.8'
services:
  # Tornado server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
      
  # Database
  mongodb:
    image: mongo
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config: